// <auto-generated />
using System;
using APIwebbanhangnhe.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace APIwebbanhangnhe.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260401082348_AddLesson6ProductsApi")]
    partial class AddLesson6ProductsApi
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("APIwebbanhangnhe.Models.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .HasMaxLength(240)
                        .HasColumnType("nvarchar(240)");

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("nvarchar(60)");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Những thẻ cầu thủ nổi bật của đội tuyển Việt Nam.",
                            DisplayOrder = 1,
                            Name = "National Team Stars"
                        },
                        new
                        {
                            Id = 2,
                            Description = "Các thẻ được săn đón từ những ngôi sao V.League.",
                            DisplayOrder = 2,
                            Name = "V.League Icons"
                        },
                        new
                        {
                            Id = 3,
                            Description = "Phiên bản hiếm với thiết kế đặc biệt dành cho người sưu tầm.",
                            DisplayOrder = 3,
                            Name = "Limited Edition"
                        },
                        new
                        {
                            Id = 4,
                            Description = "Những gương mặt trẻ đầy triển vọng của bóng đá Việt Nam.",
                            DisplayOrder = 4,
                            Name = "Rising Talents"
                        });
                });

            modelBuilder.Entity("APIwebbanhangnhe.Models.PlayerCard", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<string>("Club")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasMaxLength(600)
                        .HasColumnType("nvarchar(600)");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasMaxLength(260)
                        .HasColumnType("nvarchar(260)");

                    b.Property<string>("PlayerName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Position")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("nvarchar(60)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Rarity")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.ToTable("PlayerCards");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CategoryId = 1,
                            Club = "Cong An Ha Noi",
                            CreatedAt = new DateTime(2026, 3, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Phiên bản thẻ phủ vàng lấy cảm hứng từ lối chơi sáng tạo và khả năng tạo đột biến của Quang Hai.",
                            ImageUrl = "/images/player-cards/players/quang-hai.svg",
                            PlayerName = "Nguyen Quang Hai",
                            Position = "Midfielder",
                            Price = 790000m,
                            Rarity = "Legendary",
                            Title = "Golden Captain 2026"
                        },
                        new
                        {
                            Id = 2,
                            CategoryId = 2,
                            Club = "Becamex Binh Duong",
                            CreatedAt = new DateTime(2026, 3, 5, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Thẻ nổi bật với thông số ghi bàn ấn tượng, dành cho fan của các tiền đạo săn bàn.",
                            ImageUrl = "/images/player-cards/players/tien-linh.svg",
                            PlayerName = "Nguyen Tien Linh",
                            Position = "Forward",
                            Price = 650000m,
                            Rarity = "Ultra Rare",
                            Title = "Shining Striker 2026"
                        },
                        new
                        {
                            Id = 3,
                            CategoryId = 1,
                            Club = "Phu Dong Ninh Binh",
                            CreatedAt = new DateTime(2026, 3, 8, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Phiên bản dành cho người thích kiểm soát tuyến giữa, thiết kế lấy tông đỏ vàng chủ đạo.",
                            ImageUrl = "/images/player-cards/players/hoang-duc.svg",
                            PlayerName = "Nguyen Hoang Duc",
                            Position = "Central Midfielder",
                            Price = 560000m,
                            Rarity = "Collector",
                            Title = "Engine Room 2026"
                        },
                        new
                        {
                            Id = 4,
                            CategoryId = 4,
                            Club = "The Cong Viettel",
                            CreatedAt = new DateTime(2026, 3, 12, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Thiết kế trẻ trung, tốc độ cao, phù hợp cho bộ sưu tập những tài năng mới.",
                            ImageUrl = "/images/player-cards/players/van-khang.svg",
                            PlayerName = "Khuat Van Khang",
                            Position = "Attacking Midfielder",
                            Price = 480000m,
                            Rarity = "Limited",
                            Title = "Future Flash 2026"
                        });
                });

            modelBuilder.Entity("APIwebbanhangnhe.Models.PlayerCardImage", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("PlayerCardId")
                        .HasColumnType("int");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasMaxLength(260)
                        .HasColumnType("nvarchar(260)");

                    b.HasKey("Id");

                    b.HasIndex("PlayerCardId");

                    b.ToTable("PlayerCardImages");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            PlayerCardId = 1,
                            Url = "/images/player-cards/gallery/quang-hai-1.svg"
                        },
                        new
                        {
                            Id = 2,
                            PlayerCardId = 1,
                            Url = "/images/player-cards/gallery/quang-hai-2.svg"
                        },
                        new
                        {
                            Id = 3,
                            PlayerCardId = 2,
                            Url = "/images/player-cards/gallery/tien-linh-1.svg"
                        },
                        new
                        {
                            Id = 4,
                            PlayerCardId = 3,
                            Url = "/images/player-cards/gallery/hoang-duc-1.svg"
                        },
                        new
                        {
                            Id = 5,
                            PlayerCardId = 4,
                            Url = "/images/player-cards/gallery/van-khang-1.svg"
                        });
                });

            modelBuilder.Entity("APIwebbanhangnhe.Models.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(600)
                        .HasColumnType("nvarchar(600)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Wireless on-ear headphone for daily listening and online study.",
                            Name = "Sony WH-CH520",
                            Price = 1190000m
                        },
                        new
                        {
                            Id = 2,
                            Description = "Bluetooth headphone with strong bass and long battery life.",
                            Name = "JBL Tune 720BT",
                            Price = 1690000m
                        },
                        new
                        {
                            Id = 3,
                            Description = "Compact true wireless earbuds with a clear microphone for calls.",
                            Name = "SoundPEATS Air4 Lite",
                            Price = 1290000m
                        });
                });

            modelBuilder.Entity("APIwebbanhangnhe.Models.PlayerCard", b =>
                {
                    b.HasOne("APIwebbanhangnhe.Models.Category", "Category")
                        .WithMany("PlayerCards")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Category");
                });

            modelBuilder.Entity("APIwebbanhangnhe.Models.PlayerCardImage", b =>
                {
                    b.HasOne("APIwebbanhangnhe.Models.PlayerCard", "PlayerCard")
                        .WithMany("Images")
                        .HasForeignKey("PlayerCardId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("PlayerCard");
                });

            modelBuilder.Entity("APIwebbanhangnhe.Models.Category", b =>
                {
                    b.Navigation("PlayerCards");
                });

            modelBuilder.Entity("APIwebbanhangnhe.Models.PlayerCard", b =>
                {
                    b.Navigation("Images");
                });
#pragma warning restore 612, 618
        }
    }
}
